on: 
  pull_request:
    branches:
      - master

jobs: 
  prettier:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout default action
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master

    - name: Attach HEAD
      run: git switch -c  ${{ github.head_ref }}

    - name: Set upstream
      run: git remote add upstream git@github.com:openseattle/cvp.git

    - name: Test remotes
      run: git remote -v

    # - name: Run prettier
    #   uses: creyD/prettier_action@v3.3
    #   with: 
    #     prettier_options: --write **/*.{js,jsx,css}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
