on: 
  pull_request:
    branches:
      - master

jobs: 
  prettier:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Run prettier
      uses: creyD/prettier_action@v3.3
      with: 
        prettier_options: --write **/*.{js,jsx,css}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
